### ISSUE TITLE
Probeer in CSS selectors altijd de grootste gemene deler eerst te pakken en daarna uitzonderingen te maken

### ISSUE THREAD

**Issue by JeroenHeemskerk** [uknowwho/educom-webshop-basis-1712050575#14]
Met de code hieronder zorg je dat de inputs 400 pixels breed zijn
https://github.com/uknowwho/educom-webshop-basis-1712050575/blob/57ac1573831da3e93bc0b34396baeb2f0dc12347/styles.css#L56-L58

Echter als er nu een andere input wordt gebruikt, (bijv. `type="password"`) dan wordt deze niet meer 400px
Het is beter om ALLE inputs 400px te maken en dan eventueel voor een paar typen een uitzondering te maken:
```css
 input, select, textarea { 
     width: 400px; 
 } 

 input[type=radio], input[type=submit] { 
     width: auto; 
 } 
```
